<?php

namespace ErImageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
  public function findAllOrderedByName()
  {
    return $this->createQueryBuilder('b')
            ->orderBy('b.cottage','ASC')
            ->getQuery()
            ->getResult();
    /*
    return $this->getEntityManager()
      ->createQuery(
          'SELECT p FROM ErImageBundle:Banner p ORDER BY p.id ASC'
        )
      ->getResult();*/
  }
}
