<?php

namespace ErImageBundle\Repository;

/**
 * BucketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BucketRepository extends \Doctrine\ORM\EntityRepository
{
}
