<?php

namespace ErImageBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * BucketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BucketRepository extends \Doctrine\ORM\EntityRepository 
{
   
  public function findExpired()
  {
    return $this->createQueryBuilder('b')
            ->andWhere('b.expiresAt < :now')
            ->setParameter('now', date('Y-m-d H:i:s'))
            ->getQuery()
            ->getResult();
  }
  
  public function paginated($page = 1, $rpp = 10)
  {
   $query = $this->createQueryBuilder('b')
            ->orderBy('b.createdAt','DESC');

    $paginator = new \Knp\Component\Pager\Paginator();

    return $paginator->paginate($query,$page,$rpp);
  }
}
