<?php

namespace ErImageBundle\Repository;

/**
 * BucketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BucketRepository extends \Doctrine\ORM\EntityRepository
{
  public function findExpired()
  {
    return $this->createQueryBuilder('b')
            ->andWhere('b.expiresAt < :now')
            ->setParameter('now', date('Y-m-d H:i:s'))
            ->getQuery()
            ->getResult();
  }
}
